### ISSUE TITLE
大佬，你换的BCM94360CS2用了转接卡吗？

### ISSUE THREAD

**Issue by 1879fa** [xzz024/OC7.1-EFI-For-Dell-5593-Bigsur#11]
我看这块拆机卡需要搭配转接器使用，好像比原来的网卡长好多，长过螺丝孔了，你是怎么固定的呀？插在固态硬盘位了吗？能否看下装机图，顺便求大佬推荐下购买店铺或链接

**Comment by xzz024** [comment]
是，肯定需要转接卡，装机图已经更新贴上

**Comment by xzz024** [comment]
![bcm94360](https://user-images.githubusercontent.com/68104786/141241520-ab0528d7-541e-4860-a271-c479d3d5377f.JPG)
![转接卡](https://user-images.githubusercontent.com/68104786/141241533-dc4d3be3-d6a9-47f5-b701-e028bafcdb64.JPG)

**Comment by 1879fa** [comment]
> 是，肯定需要转接卡，装机图已经更新贴上

大佬，我的5493位置很小，转接卡用不了，eBay上38刀买了个BCM94360NG，22*30大小，不用转接，蓝牙WiFi都免驱，挺完美的

**Comment by xzz024** [comment]
wonderful

**Comment by HyramTang** [comment]
@xzz024 博主借个楼哈， @1879fa 哈喽，请问 BCM94360NG 功能效果咋样呀？AirDrop 和 Handoff 可以双向传输么？现在用 BCM94352Z / DW1560 发现只能手机 AirDrop 到电脑，电脑不能 AirDrop 到手机，Handoff 功能也是如此。
