### ISSUE TITLE
大佬 我用您制作的efi和oc安装的时候会在系统安装预计十五分钟的时候报错 好几次了 请问这是怎么回事

### ISSUE THREAD

**Issue by Wu-LH** [xzz024/OC7.1-EFI-For-Dell-5593-Bigsur#5]

**Comment by Wu-LH** [comment]
![Uploading 7A079FE3-1C06-43AC-AC09-890971FF3D7B.jpeg…]()

**Comment by Wu-LH** [comment]
![Uploading A35F5F84-6A5F-4883-B912-A1D81136BB30.jpeg…]()

**Comment by xzz024** [comment]
请问是5593的机型吗，有按照指导里面对BIOS进行设置吗

**Comment by Wu-LH** [comment]
> 请问是5593的机型吗，有按照指导里面对BIOS进行设置吗

是的 按照了

**Comment by Wu-LH** [comment]
> 请问是5593的机型吗，有按照指导里面对BIOS进行设置吗

我用的铠侠的ssd SATA

**Comment by Wu-LH** [comment]
”修改前若有win10系统，请进入先安全模式修改它 “这个是什么意思呢

**Comment by xzz024** [comment]
已经修改为AHCI了吗

**Comment by Wu-LH** [comment]
> 已经修改为AHCI了吗

修改成了 现在我是两块硬盘 自带的NVME是WIN1O 另一块自己安装的铠侠SATA SSD是安装macOS的

**Comment by xzz024** [comment]
十五分钟的时候报错：报了什么错误，上面的图片无法打开

**Comment by Wu-LH** [comment]
![IMG_0785](https://user-images.githubusercontent.com/89582300/131235388-d43e663c-938f-47a8-bf48-6b07723efce4.PNG)
![IMG_0778](https://user-images.githubusercontent.com/89582300/131235391-22ef9c49-890c-406e-8775-a9cf24237a0a.JPG)

**Comment by Wu-LH** [comment]
> 十五分钟的时候报错：报了什么错误，上面的图片无法打开

我重新上传了照片 这次可以了

**Comment by Wu-LH** [comment]
![IMG_0801](https://user-images.githubusercontent.com/89582300/131235475-4082bd8d-7280-439a-b81d-68868ac190a9.JPG)
![IMG_0803](https://user-images.githubusercontent.com/89582300/131235476-1072b80d-7605-4033-a18f-5b6cd35e81f7.JPG)
![IMG_0804](https://user-images.githubusercontent.com/89582300/131235477-0210303e-b903-4678-ba4c-dae4e5304aab.JPG)

**Comment by xzz024** [comment]
建议先尝试在NVMe安装，如果有相同问题，更换新的Macos安装包

**Comment by Wu-LH** [comment]
> 建议先尝试在NVMe安装，如果有相同问题，更换新的Macos安装包

好的 我克隆下磁盘 然后用NVMe安装 谢谢您

**Comment by xzz024** [comment]
已更新EFI，建议更换最新的EFI

**Comment by Wu-LH** [comment]
> 已更新EFI，建议更换最新的EFI

好的，请问还是用更新的EFI安装到NVMe上吗？

**Comment by xzz024** [comment]
不确定是不是你的镜像问题，可以尝试

**Comment by Wu-LH** [comment]
> 不确定是不是你的镜像问题，可以尝试

好的，我已经检验过了MD5 是符合的 我去试试 谢谢大佬

**Comment by Wu-LH** [comment]
我用u盘往NVMe上面安还是不行 我怀疑是镜像的问题🤔️ （也是剩余预计15分钟左右报错）

**Comment by Wu-LH** [comment]
我用其他镜像写入试试

**Comment by Wu-LH** [comment]
啊 大佬 我枯了 11.5和11.5.2的都是剩余十五分钟的时候出错，往NVMe写的 不会是我U盘坏了吧

**Comment by xzz024** [comment]
加我q 3124181198

**Comment by Wu-LH** [comment]
谢谢大佬> 加我q 3124181198

**Comment by xzz024** [comment]
# 问题已解决原因：

BIOS处于最新的1.16.0版本，该版本对于已安装会造成闪退、无法更新等问题。未安装用户安装阶段会报错。降级BIOS即可解决。
