### ISSUE TITLE
双硬盘mac+win10，win10蓝屏进不去？

### ISSUE THREAD

**Issue by yflwz** [xzz024/OC7.1-EFI-For-Dell-5593-Bigsur#7]
双系统分别安装在不同的硬盘，按F12选择硬盘启动都可以进，但是通过OC启动后，tftfrc选择win的时候引导后报错，蓝屏。

**Comment by xzz024** [comment]
oc官方版可以进win，但不推荐。可以自行尝试Mod版本

**Comment by yflwz** [comment]
下载了新的0.78版本，windows引导还是报ACPI_BIOS_ERROR错并蓝屏，更换过官方版本的OpenCore-0.7.8-RELEASE.zip也一样，能提供一下MOD版本的吗？目前除了HDMI输出不行，就差这一个问题了。
